name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ env.SHORT_SHA }}
    steps:

      -
        name: Set Short SHA
        shell: bash
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mosesade/python-app:${{ env.SHORT_SHA }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      -
        uses: actions/checkout@v3

      -
        name: Modify values file
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.commit_id }}
          apt install python3.12-venv
          pip install yq
          yq -Yi '.image.tag = "${{ needs.ci.outputs.commit_id }}"' charts/python-app/values.yaml

      -
        name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'update values.yaml with commit ${{ needs.ci.outputs.commit_id }}'

      -
        name: Install Argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      -
        name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGO_PASS }}
          argocd app sync python-app


